export type Fact =
	| { kind: "email"; email: string }
	| { kind: "call"; call: string }
	| { kind: "msg"; msg: string };

export interface EngObjectEvent {
	id: string;
	timestamp: string;    // "YYYY-MM-DDTHH:mm"
	note: string;         // plain text; first line shown in TableList
	taskRefs: string[];   // IDs of EngObjectTasks touched by this event
	facts: Fact[];
	isAutoEdit?: boolean; // true = auto-generated by edit; accumulates
}

export interface EngObjectTask {
	id: string;
	note: string;         // plain text; first line is the summary shown in list
	status: "pending" | "in-progress" | "done";
	deadline?: string;    // "YYYY-MM-DD"
	eventRefs: string[];  // IDs of events that opened/changed/closed this task
}

export interface EngObjectPerson {
	kind?: "client" | "subcontractor";  // drives grouping; absent = "other"
	label: string;        // free-form display: "Замовник", "Куратор", etc.
	contactId: string;
}

export type EngObjectStatus = "ongoing" | "completed";

export interface EngObject {
	id: string;
	name: string;
	status: EngObjectStatus;
	completedDate?: string;   // "YYYY-MM-DD"
	people: EngObjectPerson[];
	pay?: string;             // free-form: "120 000 грн", "договірна"
	notes: string;
	tasks: EngObjectTask[];
	history: EngObjectEvent[]; // oldest first; latest = history.at(-1)
	links: { directory?: string };
}

export interface Extra {
	id: string;
	name: string;
	status: "ongoing" | "completed";
	completedDate?: string;
	people: EngObjectPerson[];
	pay?: string;
	notes: string;
	history: EngObjectEvent[];
	linkToObject?: string;
}

export interface Contact {
	id: string;
	kind?: "client" | "subcontractor";
	sync: {
		origin: "local" | "google";
		isSynced: boolean;
	};
	name: {
		first?: string;
		middle?: string;
		last?: string;
	};
	email: {
		lbl?: string;
		val: string;
	}[];
	phone: {
		lbl?: string;
		val: string;
	}[];
	notes: string;
}

export interface User {
	id: string;
	email: string;
	passwordHash: string; // plaintext in demo
	name: { first: string; last: string };
	gender: string;
	birthDate: string; // "YYYY-MM-DD"
}
